const products = [
  {
    name: "Mouse",
    basic_feature: "Wireless",
    src: "img/mouse.jpg",
    product_description:
      "Ergonomic wireless mouse designed for comfortable all-day use. Features adjustable DPI settings for precise control, silent click buttons for distraction-free work, and long-lasting rechargeable battery support.",
    price: 799,
    sale: true,
    discount: 20,
    featured_product: true,
    rating: 5,
    rating_count: 123,
    manufactured_by: "Rai Corporation",
    in_stock: true,
    features: {
      Connectivity_Options: "2.4GHz Wireless, Bluetooth 5.0",
      Dimensions: "11 x 6 x 3.5 cm",
      Weight: "85g",
      Color: "Black",
      Safety_Features: "Overcharge protection",
      Power_Source: "Rechargeable Battery",
      Ports: "USB Receiver",
      Build_Material: "ABS Plastic",
    },
  },
  {
    name: "Keyboard",
    basic_feature: "Mechanical",
    src: "img/key.jpg",
    product_description:
      "High-performance RGB backlit mechanical keyboard equipped with tactile blue switches for satisfying feedback. Built for gamers and professionals, offering durability, fast response time, and customizable lighting effects.",
    price: 2499,
    sale: false,
    discount: 0,
    featured_product: false,
    rating: 4,
    rating_count: 142,
    manufactured_by: "KeyPro Industries",
    in_stock: false,
    features: {
      Connectivity_Options: "Wired USB",
      Dimensions: "44 x 13 x 4 cm",
      Weight: "950g",
      Color: "Black",
      Safety_Features: "Spill resistant",
      Power_Source: "USB Powered",
      Ports: "USB 2.0",
      Build_Material: "Aluminum + ABS",
    },
  },
  {
    name: "Headphones",
    basic_feature: "Bluetooth",
    src: "img/headphones.jpg",
    product_description:
      "Premium noise-cancelling over-ear headphones delivering deep bass and crystal-clear sound. Supports Bluetooth connectivity, long battery life, and a comfortable cushioned design for extended listening sessions.",
    price: 3499,
    sale: true,
    discount: 30,
    featured_product: false,
    rating: 3,
    rating_count: 12,
    manufactured_by: "SoundMax",
    in_stock: true,
    features: {
      Connectivity_Options: "Bluetooth 5.2, AUX",
      Dimensions: "18 x 15 x 7 cm",
      Weight: "220g",
      Color: "White",
      Safety_Features: "Overheat protection",
      Power_Source: "Rechargeable Battery",
      Ports: "USB-C, 3.5mm Jack",
      Build_Material: "Polycarbonate + Foam",
    },
  },
  {
    name: "Camera",
    basic_feature: "Digital",
    src: "img/camera.jpg",
    product_description:
      "Advanced 24MP DSLR camera capable of capturing stunning high-resolution photos and 4K video recordings. Designed for photography enthusiasts and professionals, featuring wireless connectivity and a durable body.",
    price: 45999,
    sale: false,
    discount: 0,
    featured_product: false,
    in_stock: true,
    rating: 2,
    rating_count: 156,
    manufactured_by: "Canonix",
    features: {
      Connectivity_Options: "WiFi, Bluetooth",
      Dimensions: "13 x 10 x 7.5 cm",
      Weight: "450g",
      Color: "Black",
      Safety_Features: "Shock resistant body",
      Power_Source: "Lithium-ion Battery",
      Ports: "HDMI, USB-C",
      Build_Material: "Magnesium Alloy",
    },
  },
  {
    name: "Charging Cable",
    basic_feature: "USB-C",
    src: "img/cable.jpg",
    product_description:
      "Durable fast-charging USB-C cable supporting up to 60W power delivery. Built with reinforced nylon braiding for extra strength and long-term use, ensuring safe and efficient charging for compatible devices.",
    price: 499,
    sale: true,
    discount: 20,
    featured_product: false,
    rating: 1,
    rating_count: 129,
    manufactured_by: "Rai Corporation",
    in_stock: true,
    features: {
      Connectivity_Options: "USB-C to USB-C",
      Dimensions: "1 meter length",
      Weight: "40g",
      Color: "Red",
      Safety_Features: "Short-circuit protection",
      Power_Source: "N/A",
      Ports: "USB-C",
      Build_Material: "Nylon Braided",
    },
  },
];